# Site settings
title: Micah Dylan
email: md@micahdylan.com
description: > # this means to ignore newlines until "baseurl:"
  Learning is life. I started this blog as a place to share and explore ideas. I hope, by sharing, to refine my ideas and learn new things from those who visit. Thank you for coming by! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.micahdylan.com" # the base hostname & protocol for your site
twitter_username: micahdylan
github_username:  micahdylan

# Build settings
markdown: kramdown
